### ISSUE TITLE
Allow to use un-hidden `agora.yaml` files for configuration

### ISSUE THREAD

**Issue by soenkehahn** [agora-org/agora#118]
In case agora hosters want to serve the configuration files through agora. Depends on #117.

**Comment by neunenak** [comment]
Is this necessarily a good idea? It seems to me that it's simpler for agora to declare that a file named exactly `.agora.yaml` is the only possible authoritative configuration file for a directory. If an agora hoster does want to serve the configuration file, they can easily copy its contents to a file called `agora.yaml` (or whatever other name they want). The only benefit I can see to having non-hidden `agora.yaml` be public is that it means configuration file changes are manifested immediately in the publicly-available file without having to go through that extra copy step; but I think the number of people who will want to serve their own server's configuration file is small enough removing an extra `cp .agora.yaml agora.yaml` step isn't worth supporting.

**Comment by neunenak** [comment]
Maybe another way to solve this problem would be for the config file to explicitly allow serving of specific dotfiles in a directory, which could be configured to serve `.agora.yaml` in the same way as any other dotfilefile.

**Comment by soenkehahn** [comment]
Yeah, I'm not sure anymore what the use-case was that we had in mind for this. I'd be fine closing this. @casey: Do you remember details?

**Comment by casey** [comment]
I'm a bit hazy on it, but I think the use-case was to allow visitors to an Agora instance to be able to easily see the instance's configuration, both for informative and for pedagogical reasons.

We could definitely just close this, and wait until someone wants it, or close in favor of an option to serve hidden files, instead of making it specific to `.agora.yaml`.

**Comment by soenkehahn** [comment]
Yeah. I'll close this then. Once it comes up again we should have a much better idea what we actually want.
