### ISSUE TITLE
Host a piece of video content

### ISSUE THREAD

**Issue by casey** [agora-org/agora#213]
- A great piece of content to host is The General with Buster Keaton
- Should support random access
- Should figure out the best container and codec (
- Should figure out if we should use the browser's built in video player or use a dedicated player

**Comment by yzernik** [comment]
Video appears to be working for me:
http://tmcalh6tjskfmnjsipi4tqlzcr4ltracuup6gp4vkyi4e5s42ooef2yd.onion/files/Rick_Astley_Never_Gonna_Give_You_Up.mp4?invoice=bfd70a78fd402225c1c51586c4e6436f7f1fad286eec9cdbca1880b766bd25e0

**Comment by casey** [comment]
Nice. I think this issue is for having more specific support for video, like playing in a dedicated player. Not sure it's useful to leave open though.
